import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider appearance={
        {
          layout: {
            logoImageUrl: "/icons/yoom-logo.svg",
            socialButtonsVariant:'iconButton'
          },
          variables: {
            colorPrimary: 'rgb(37 99 235)',
            colorBackground: '#1C1F2E',
            colorText: '#fff',
            colorInputBackground: '#252a41',
            colorInputText: '#fff'
          }
        }
      }>
        <body className={`${inter.className} bg-dark-2`}>{children}</body>
      </ClerkProvider>
    </html>
  );
}
